version: '3.9'

services:
  db:
    container_name: league-point-db
    build:
      dockerfile: docker/db/Dockerfile
      context: .
    # environment:
    #   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
    #   MYSQL_USER: ${MYSQL_USER:?err}
    #   MYSQL_PASSWORD: ${MYSQL_PASSWORD:?err}
    #   MYSQL_DATABASE: ${MYSQL_DATABASE:?err}
    volumes:
      - type: volume
        source: league-point-db-volume
        target: /var/lib/mysql
      - type: bind
        source: ./docker/db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    ports:
      - 13306:3306
    env_file:
      - ./confidential/.env

volumes:
  league-point-db-volume:
